# Doctrine Configuration
doctrine:
    dbal:
        driver:   %pdo_mysql%
        host:     %localhost%
        port:     %8889%
        dbname:   %bug-tracker%
        user:     %root%
        password: %%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true